image:
  repository: REPLACE_ME.dkr.ecr.REPLACE_REGION.amazonaws.com/voting-api
  tag: v-metrics
  pullPolicy: IfNotPresent

replicaCount: 2

autoscaling:
  enabled: true

gateway:
  enabled: true
  createGateway: false
  className: aws-alb
  host: voting.example.com
  parentRef:
    name: platform-gateway
    namespace: gateway-system

postgres:
  auth:
    existingSecret: voting-postgres-prod
  persistence:
    size: 20Gi
    storageClass: gp3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
