apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: team-a
  labels:
    team: team-a
    app: web
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>Team A Demo App</title>
        <style>
          body {
            background-color: green;
            margin: 0;
          }
          h3 {
            text-align: center;
            padding-top: 1rem;
            color: white;
          }
        </style>
      </head>
      <body>
        <h3>this is a demo app</h3>
      </body>
    </html>
