apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: voting-api
  namespace: voting
spec:
  targetGroupARN: arn:aws:elasticloadbalancing:ca-central-1:099139718958:loadbalancer/app/voting-dev-alb/20f92b63fc1eddc3
  targetType: ip
  serviceRef:
    name: voting-app-api
    port: 8000
