apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: {{ .Values.name }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultLimitCpu | quote }}
        memory: {{ .Values.limitRange.defaultLimitMemory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu | quote }}
        memory: {{ .Values.limitRange.defaultRequestMemory | quote }}
