apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ .Values.name }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
    persistentvolumeclaims: {{ .Values.quota.persistentVolumeClaims | quote }}
