# apiVersion: argoproj.io/v1alpha1
# kind: ClusterAnalysisTemplate
# metadata:
#   name: error-budget-burn
# spec:
#   args:
#     - name: service
#     - name: namespace
#     - name: slo
#       value: "99.5"
#     - name: burnRate
#       value: "6"
#   metrics:
#     - name: error-budget-burn
#       interval: 60s
#       count: 5
#       # burn = errorRate / errorBudget. errorBudget = (100-slo)/100.
#       # successCondition: burn stays under burnRate multiplier.
#       successCondition: result[0] < {{args.burnRate}}
#       failureLimit: 2
#       provider:
#         prometheus:
#           address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
#           query: |
#             (
#               sum(rate(istio_requests_total{
#                 destination_service_name="{{args.service}}",
#                 destination_service_namespace="{{args.namespace}}",
#                 response_code=~"5.."
#               }[1h]))
#               /
#               sum(rate(istio_requests_total{
#                 destination_service_name="{{args.service}}",
#                 destination_service_namespace="{{args.namespace}}"
#               }[1h]))
#             ) / ((100 - {{args.slo}}) / 100)
