apiVersion: v1
kind: Namespace
metadata:
  name: karpenter-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: karpenter-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        karpenter.sh/capacity-type: on-demand
      containers:
        - name: inflate
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
